### ISSUE TITLE
Do we expect the TimestampEstimator value to go backward in time?

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/timinglibs#10]
When I enable some of the TRACE messages in the TimestampEstimator and the FakeHSIEventGenerator, I see the reported "current timestamp estimate" sometimes going from a larger value to a smaller value, instead of always increasing.  Is this expected?

Here is a snippet of the TRACE messages (please note that messages are in reverse time order):

```
   663 05-12 20:53:19.420626   56795   57223   5          TimestampEstimator D10 estimator_thread_fn: Got a TimeSync timestamp = 79759095189179468, system time = 1620870799401360 when current timestamp estimate was 79759095190127568. diff=948100
   664 05-12 20:53:19.420619   56795   57223   5          TimestampEstimator D10 estimator_thread_fn: Got a TimeSync timestamp = 79759095189660968, system time = 1620870799401331 when current timestamp estimate was 79759095190127568. diff=466600
   665 05-12 20:53:19.410558   56795   57223   5          TimestampEstimator D10 estimator_thread_fn: Got a TimeSync timestamp = 79759095189449768, system time = 1620870799401343 when current timestamp estimate was 79759095194128068. diff=4678300
   666 05-12 20:53:19.410558   56795   57223   5          TimestampEstimator D10 estimator_thread_fn: Got a TimeSync timestamp = 79759095189448268, system time = 1620870799401337 when current timestamp estimate was 79759095194128068. diff=4679800
```

As you can see, the estimates were

- 79759095190127568, line 664, message time 19.42 seconds
- 79759095194128068, line 665, message time 19.41 seconds

And, the later estimate (line 664) is less than the earlier estimate (line 665).

**Comment by strilov** [comment]
Hi Kurt,

In this case I think it would be expected. The timestamp estimate is ahead of that of the timestamp of the incoming TimeSync messages, so the TimestampEstimator is adjusting (and thereby reducing) its timestamp estimate. 

It'd be interesting to trace how the estimate gets ahead of the timestamp in the TimeSync messages.

**Comment by philiprodrigues** [comment]
I think the reason this was happening a lot was because of the missing slowdown factor in the config, so now that that's fixed (https://github.com/DUNE-DAQ/minidaqapp/pull/46) we won't see it as much. I think it's still possible for the timestamp to go backwards in more limited circumstances, if the separate readout units get out of sync, so we should probably protect against this.
