### ISSUE TITLE
Add configurable offset for FakeHSIEventGenerator?

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/timinglibs#11]
In MiniDAQApp system tests for release v2.6.0, we have noticed instances in which the timestamps from the FakeHSIEventGenerator are noticeably ahead of the timestamps in the Readout subsystem latency buffers and the timesync messages that are being sent from Readout to the FakeHSIEventGenerator.  This issue became apparent when we noticed TriggerRecords at end run that had empty Fragments, and we found that those empty fragments were caused by Data Requests that had time values later than what was in the Readout latency buffer.

It would be great for that to be understood and possibly changed, but we would also like to request a configuration parameter for FakeHSIEventGenerator that would allow us to specify an offset for the HSIEvent timestamps.  It would be great if this value could be either positive or negative (in order to move the HSI timestamp earlier or later).

**Comment by strilov** [comment]
Hi Kurt,

We can definitely investigate that. The TimestampEstimator is supposed to track (up or down) the timestamp of the TimeSync messages. Do you have a sense if the timestamps are aligned for a a while, and start to diverge after a certain period of time?

In the meantime, I'll add a timestamp offset conf parameter to the FakeHSIEventGenerator module.

**Comment by strilov** [comment]
I'm guessing you'd like the offset to be applied at every new timestamp estimate? Would this affect timestamp estimates which are already aligned?

**Comment by bieryAtFnal** [comment]
I will gather some information on whether the timestamps are aligned for a while and start to diverge after a certain period of time.  My sense is that it is somewhat unpredictable.

Yes, the offset would be applied every time.  In a local modification that I made to the FakeHSIEventGenerator (for testing), I made the following change.  This is the sort of thing that I had in mind.  When I talked with Phil earlier today about this, he recalled a configuration parameter like this in earlier generations of the code, so he may have opinions also.

```
diff --git a/plugins/FakeHSIEventGenerator.cpp b/plugins/FakeHSIEventGenerator.cpp
index 74a7431..219b0e0 100644
--- a/plugins/FakeHSIEventGenerator.cpp
+++ b/plugins/FakeHSIEventGenerator.cpp
@@ -163,6 +163,9 @@ FakeHSIEventGenerator::generate_hsievents(std::atomic<bool>& running_flag)
     if (signal_map) {
       
       dfmessages::timestamp_t ts = m_timestamp_estimator->get_timestamp_estimate();
+
+      // KAB hack
+      ts -= 3500000;
       
       ++m_generated_counter;
```

**Comment by bieryAtFnal** [comment]
[HSIMessages_13MayA.txt](https://github.com/DUNE-DAQ/timinglibs/files/6473131/HSIMessages_13MayA.txt)
 Here are some TRACE messages (please note the reverse time order of the messages).

Some of the "diff"s seem large (> 3,000,000).
But, there doesn't seem to be a pattern of increasing offsets.

**Comment by strilov** [comment]
Thanks Kurt. I'll look into this.

In the mean time, here is a branch which has the configurable timestamp offset: https://github.com/DUNE-DAQ/timinglibs/tree/feature/fake_hsi_gen_timestamp_offset

**Comment by philiprodrigues** [comment]
@strilov that branch looks reasonable to me. I think it would be worth adding two bits of documentation, then PR and merge:

1. The sign on the offset (positive values make the `HSIEvent` timestamp larger than the current timestamp estimate, rather than the other way round)
2. Note that the units of the offset are ticks (rather than, say seconds)

**Comment by strilov** [comment]
Thanks @philiprodrigues. PR, with documentation added, here: https://github.com/DUNE-DAQ/timinglibs/pull/13.
