### ISSUE TITLE
Can we remove the receiving of TimeSync messages from TimestampEstimator?

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/timinglibs#49]
Once the conversion to use the Unified Communications API is done, can we consider the possibility of removing the all knowledge of queues and connection from TimestampEstimator?

This coupling has been the source of extra work a couple of times now, and it somewhat violates the concept of having each piece of code do one (or a small) number of things well.  IMO, TimestampEstimator should know how to do that: estimate timestamps.  The receiving of TimeSync events should be handled elsewhere.

**Comment by dingp** [comment]
@strilov @bieryAtFnal Do we want (can we have) the feature in 3.0? I am assigning it to 3.0 for now so that we remember to check on it, and defer it to future release if needed.

**Comment by bieryAtFnal** [comment]
@dingp , at this point in the development cycle, my vote would be to defer this to v3.1.0.  It is something that would be nice to have, but it is not necessary right now, and runs the risk of introducing problems.

**Comment by alessandrothea** [comment]
@strilov @bieryAtFnal  Shall these PRs be merged now that 4.1 is done?

**Comment by bieryAtFnal** [comment]
Closing this now that the latest set of associated PRs have been reviewed and merged.
