### ISSUE TITLE
Fake HSI time gets out-of-sync with readout time sync messages?

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/timinglibs#9]
In tests of multiple runs within a single instance of the DAQ, I've noticed occasional instances in which there is very little data written to the output file.  I believe that this is because the time window in the TriggerDecision (window_begin and window_end) temporarily gets out of sync with what the Readout subsystem thinks the time is.  

I've attached a copy of some entries from the TRACE file in one instance where this happened,  The TRACE messages correspond to 4 runs of about 20 seconds each.  The entries in the file are from the sending of the HSI event to the Trigger and warning messages from the Readout subsystem when it can't find the requested time window in its buffer.  

The command that I used to run the system was the following:

- `tmprun=51261437; nanorc mdapp_6proc boot init conf start ${tmprun} wait 3 resume wait 20 pause stop wait 2 start ${tmprun} wait 3 resume wait 20 pause stop wait 2 start ${tmprun} wait 3 resume wait 20 stop wait 1 start ${tmprun} wait 3 resume wait 20 stop wait 1 scrap terminate`

and the command that I used to generate the 6proc config was the following:

- `python -m minidaqapp.nanorc.mdapp_multiru_gen --host-ru localhost --host-ru localhost --host-ru localhost -d /scratch/biery/data/frames.bin -o . -s 10 -n 5 --enable-trace mdapp_6proc`

**Comment by bieryAtFnal** [comment]
[HSI_11May.txt](https://github.com/DUNE-DAQ/timinglibs/files/6468794/HSI_11May.txt)

**Comment by philiprodrigues** [comment]
I think this is fixed by https://github.com/DUNE-DAQ/minidaqapp/pull/46
